export const ANTHROPIC_MAIN_MODEL =
  process.env.ANTHROPIC_MAIN_MODEL ?? "claude-sonnet-4-6";

export const ANTHROPIC_FAST_MODEL =
  process.env.ANTHROPIC_FAST_MODEL ?? "claude-haiku-4-5-20251001";

export const ANTHROPIC_PREMIUM_READING_MODEL =
  process.env.ANTHROPIC_PREMIUM_READING_MODEL ?? ANTHROPIC_MAIN_MODEL;

export const ANTHROPIC_STANDARD_READING_MODEL =
  process.env.ANTHROPIC_STANDARD_READING_MODEL ?? ANTHROPIC_FAST_MODEL;
